# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Glib
version:      1.072
version_from: Glib.pm
installdirs:  site
requires:
    ExtUtils::Depends:             0.200
    ExtUtils::PkgConfig:           1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
